language: ruby
rvm:
- 2.4.1

script: 
- bundle install
- bundle exec jekyll build

before_deploy:
  - chmod +x deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true

# if required to whitelist only master and disable builds on all other branch pushes

# branches:
#   only:
#   - master

sudo: false

cache: bundler